import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import WagmiProviderConfig from "@/lib/providers/web3-provider";
import { headers } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: 'Agentic Poc',
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = headers()
  const cookies = header.get('cookie')
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WagmiProviderConfig cookies={cookies}>
         {children}
        </WagmiProviderConfig>
      </body>
    </html>
  );
}
